# -*- coding: utf-8 -*-
"""Cross_Market_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3nMLokbOrzjwavJ0g-5YXxycF1CeVwa

--------------------------------------------------------------------------------
# **Author** : ***Mohamed Halith M K***
## **Title**  : ***Cross Market Analysis***
### ***GUVI Mini Project - 1***
--------------------------------------------------------------------------------

# Data Collection
"""

import requests
import time
import pandas as pd

data_crypto = []

for page_num in range(1,6):
  url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
  response = requests.get(url)
  if response.status_code == 200:
    data_crypto.extend(response.json()) # Extend the list with data from current page
    print(f"Collected data from page {page_num}")
  else:
    print(f"Error collecting data from page {page_num}: {response.status_code}")
    page_num += 1
  time.sleep(5) # Increased wait time to 1 second to avoid rate limiting

print ("==========================================")
print(f"Total data collected: {len(data_crypto)}")

import pprint

pprint.pprint(data_crypto)

print(f"Total Data of Cryptocurrencies: {len(data_crypto)}")

"""**Column Rename**"""

rename_columns = []

for i in data_crypto:
  rename_columns.append(dict(
      coin_id = i['id'],
      symbol = i['symbol'],
      coin_name = i['name'],
      current_price = i['current_price'],
      market_cap = i['market_cap'],
      market_cap_rank = i['market_cap_rank'],
      total_volume = i['total_volume'],
      circulating_supply = i['circulating_supply'],
      total_supply = i['total_supply'],
      ath = i['ath'],
      atl = i['atl'],
      last_updated = i['last_updated']
      ))

pprint.pprint(rename_columns)

print(f"Total data for filtered columns: {len(rename_columns)}")

crypto_df = pd.DataFrame(rename_columns) #visualizing data in pandas
crypto_df

# date only extract from last_updated
crypto_df["last_updated"] = pd.to_datetime(crypto_df["last_updated"]).dt.date
crypto_df

crypto_df.head()

"""**Top Coins Historical Prices**"""

# getting data for top coins price history
all_coins = []

coin_ids = ['bitcoin','ethereum','tether','binancecoin','ripple']

for i in coin_ids:
  url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
  response=requests.get(url)

  if response.status_code == 200:
    coins=response.json()
    prices = coins["prices"]#extracting data to table and converting ms to datestamp
    time.sleep(5)

    for ts, price in prices:
      all_coins.append({"coin_id": i,"date": pd.to_datetime(ts, unit="ms"),"price": price})

top_coins_df = pd.DataFrame(all_coins)

top_coins_df

# date only extract from datestamp
top_coins_df["date"] = pd.to_datetime(top_coins_df["date"]).dt.date
top_coins_df

"""**Oil Prices(WTI Crude)**"""

# data collection from csv file - github link
import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

# extracting data from Jan 2020 - Feb 2026 ==> mentioned in project file
oil_df['Date'] = pd.to_datetime(oil_df['Date'])
start_date = pd.to_datetime('2020-01-01')
end_date   = pd.to_datetime('2026-02-23')

oil_df = oil_df[(oil_df['Date'] >= start_date) & (oil_df['Date'] <= end_date)]

oil_df

oil_df = oil_df.reset_index(drop=True)
oil_df

"""**Stock Prices (Yahoo Finance API)**"""

# collect following stocks data from Yahoo Finance API
import yfinance as YF

tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-23"

stk_df = YF.download(tickers, start=start_date, end=end_date, group_by="ticker")
stk_df.head()

# colleting data separately for easy undersating
# "^NSEI"
stocks1_df = stk_df["^NSEI"].reset_index()
stocks1_df.head()

# adding column ==> "tickers"
stocks1_df.insert(1, "Ticker", "^NSEI")
stocks1_df

# finding nulls from collected data
print(stocks1_df.isnull().sum())

# remove null for clear undersating
stocks1_df = stocks1_df.dropna()

stocks1_df

print(stocks1_df.isnull().sum())

# "^IXIC"
stocks2_df = stk_df["^IXIC"].reset_index()

stocks2_df.insert(1, "Ticker", "^IXIC") # inserting column

stocks2_df = stocks2_df.dropna() # removing nulls

stocks2_df

stocks2_df.isnull().sum() # checking null values are removed

# "^GSPC"
stocks3_df = stk_df["^GSPC"].reset_index()

stocks3_df.insert(1, "Ticker", "^GSPC") # inserting column

stocks3_df = stocks3_df.dropna() # removing nulls

stocks3_df

stocks3_df.isnull().sum() # checking null values are removed

# merging all stocks after cleaning nulls and adding column for comparision
stks_df = pd.concat([stocks1_df, stocks2_df, stocks3_df])
stks_df

stks_df.isnull().sum() # verify nulls after merging all three data

stks_df

"""# **Saving data into csv**"""

crypto_df = crypto_df.to_csv("crypto_df.csv", index=False)

top_coins_df = top_coins_df.to_csv("top_coins_df.csv", index=False)

oil_df = oil_df.to_csv("oil_df.csv", index=False)

stks_df = stks_df.to_csv("stks_df.csv", index=False)

# reading collected csv data
crypto_df = pd.read_csv("crypto_df.csv")
crypto_df

top_coins_df = pd.read_csv("top_coins_df.csv")
top_coins_df

oil_df = pd.read_csv("oil_df.csv")
oil_df

stks_df = pd.read_csv("stks_df.csv")
stks_df
