# -*- coding: utf-8 -*-
"""Cross_Market_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3nMLokbOrzjwavJ0g-5YXxycF1CeVwa

--------------------------------------------------------------------------------
# **Author** : ***Mohamed Halith M K***
## **Title**  : ***Cross Market Analysis***
### ***GUVI Mini Project - 1***
--------------------------------------------------------------------------------

# Data Collection
"""

import requests
import time
import pandas as pd

data_crypto = []

for page_num in range(1,6):
  url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
  response = requests.get(url)
  if response.status_code == 200:
    data_crypto.extend(response.json()) # Extend the list with data from current page
    print(f"Collected data from page {page_num}")
  else:
    print(f"Error collecting data from page {page_num}: {response.status_code}")
    page_num += 1
  time.sleep(5) # Increased wait time to 1 second to avoid rate limiting

print ("==========================================")
print(f"Total data collected: {len(data_crypto)}")

import pprint

pprint.pprint(data_crypto)

print(f"Total Data of Cryptocurrencies: {len(data_crypto)}")

"""**Column Rename**"""

rename_columns = []

for i in data_crypto:
  rename_columns.append(dict(
      coin_id = i['id'],
      symbol = i['symbol'],
      coin_name = i['name'],
      current_price = i['current_price'],
      market_cap = i['market_cap'],
      market_cap_rank = i['market_cap_rank'],
      total_volume = i['total_volume'],
      circulating_supply = i['circulating_supply'],
      total_supply = i['total_supply'],
      ath = i['ath'],
      atl = i['atl'],
      last_updated = i['last_updated']
      ))

pprint.pprint(rename_columns)

print(f"Total data for filtered columns: {len(rename_columns)}")

crypto_df = pd.DataFrame(rename_columns) #visualizing data in pandas
crypto_df

# date only extract from last_updated
crypto_df["last_updated"] = pd.to_datetime(crypto_df["last_updated"]).dt.date
crypto_df

crypto_df.head()

"""**Top Coins Historical Prices**"""

# getting data for top coins price history
all_coins = []

coin_ids = ['bitcoin','ethereum','tether','binancecoin','ripple']

for i in coin_ids:
  url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
  response=requests.get(url)

  if response.status_code == 200:
    coins=response.json()
    prices = coins["prices"]#extracting data to table and converting ms to datestamp
    time.sleep(5)

    for ts, price in prices:
      all_coins.append({"coin_id": i,"date": pd.to_datetime(ts, unit="ms"),"price": price})

top_coins_df = pd.DataFrame(all_coins)

top_coins_df

# date only extract from datestamp
top_coins_df["date"] = pd.to_datetime(top_coins_df["date"]).dt.date
top_coins_df

"""**Oil Prices(WTI Crude)**"""

# data collection from csv file - github link
import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

# extracting data from Jan 2020 - Feb 2026 ==> mentioned in project file
oil_df['Date'] = pd.to_datetime(oil_df['Date'])
start_date = pd.to_datetime('2020-01-01')
end_date   = pd.to_datetime('2026-02-23')

oil_df = oil_df[(oil_df['Date'] >= start_date) & (oil_df['Date'] <= end_date)]

oil_df

oil_df = oil_df.reset_index(drop=True)
oil_df

"""**Stock Prices (Yahoo Finance API)**"""

# collect following stocks data from Yahoo Finance API
import yfinance as YF

tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-23"

stk_df = YF.download(tickers, start=start_date, end=end_date, group_by="ticker")
stk_df.head()

# colleting data separately for easy undersating
# "^NSEI"
stocks1_df = stk_df["^NSEI"].reset_index()
stocks1_df.head()

# adding column ==> "tickers"
stocks1_df.insert(1, "Ticker", "^NSEI")
stocks1_df

# finding nulls from collected data
print(stocks1_df.isnull().sum())

# remove null for clear undersating
stocks1_df = stocks1_df.dropna()

stocks1_df

print(stocks1_df.isnull().sum())

# "^IXIC"
stocks2_df = stk_df["^IXIC"].reset_index()

stocks2_df.insert(1, "Ticker", "^IXIC") # inserting column

stocks2_df = stocks2_df.dropna() # removing nulls

stocks2_df

stocks2_df.isnull().sum() # checking null values are removed

# "^GSPC"
stocks3_df = stk_df["^GSPC"].reset_index()

stocks3_df.insert(1, "Ticker", "^GSPC") # inserting column

stocks3_df = stocks3_df.dropna() # removing nulls

stocks3_df

stocks3_df.isnull().sum() # checking null values are removed

# merging all stocks after cleaning nulls and adding column for comparision
stks_df = pd.concat([stocks1_df, stocks2_df, stocks3_df])
stks_df

stks_df.isnull().sum() # verify nulls after merging all three data

stks_df

"""# **Saving data into csv**"""

crypto_df = crypto_df.to_csv("crypto_df.csv", index=False)

top_coins_df = top_coins_df.to_csv("top_coins_df.csv", index=False)

oil_df = oil_df.to_csv("oil_df.csv", index=False)

stks_df = stks_df.to_csv("stks_df.csv", index=False)

# reading collected csv data
crypto_df = pd.read_csv("crypto_df.csv")
crypto_df

top_coins_df = pd.read_csv("top_coins_df.csv")
top_coins_df

oil_df = pd.read_csv("oil_df.csv")
oil_df

stks_df = pd.read_csv("stks_df.csv")
stks_df

"""# **SQL connection Table Creation**"""

pip install mysql-connector-python

import mysql.connector

conn = mysql.connector.connect(
    host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
    user = "3fXqCw6nxxduoS8.root",
    password = "u2dctQHUVuOXcZhS",
    port = 4000
)

cma = conn.cursor()

cma.execute("DROP DATABASE IF EXISTS Cross_Market_Analysis")
conn.commit()

cma.execute("CREATE DATABASE Cross_Market_Analysis")
conn.commit()

cma.execute("show databases")
cma.fetchall()

cma.execute("use Cross_Market_Analysis")

# creating tables for cryptocurrencies

cma.execute("""CREATE TABLE cryptocurrencies
                 (id VARCHAR(50) PRIMARY KEY,
                 symbol VARCHAR(10),
                 name VARCHAR(100),
                 current_price DECIMAL(18, 6),
                 market_cap BIGINT,
                 market_cap_rank INT,
                 total_volume BIGINT,
                 circulating_supply DECIMAL(20, 6),
                 total_supply DECIMAL(20, 6),
                 ath DECIMAL(18, 6),
                 atl DECIMAL(18, 6),
                 date DATE
                 );

                 """)
conn.commit() # apply the changes to the sqlite3

#creating table for Crypto_prices

cma.execute("""CREATE TABLE top_coins
                 (coin_id VARCHAR(50),
                 date DATE,
                 price DECIMAL(18, 6)
                 );

                 """)
conn.commit()

#creating table for Oil_prices

cma.execute("""CREATE TABLE oil_prices
                 (date DATE PRIMARY KEY,
                 price_INR DECIMAL(18, 6)
                 );

                 """)
conn.commit()

#creating table for Stock_prices
cma.execute("""CREATE TABLE stk_prices
                 (date DATE,
                 open DECIMAL(18, 6),
                 high DECIMAL(18, 6),
                 low DECIMAL(18, 6),
                 close DECIMAL(18, 6),
                 volume BIGINT,
                 ticker VARCHAR(20)
                 );

                 """)
conn.commit()

cma.execute("show tables")
cma.fetchall()

"""# **Pushing data frames in to SQL and create sql engine**"""

pip install pandas sqlalchemy mysql-connector-python

from sqlalchemy import create_engine

engine = create_engine("mysql+mysqlconnector://3fXqCw6nxxduoS8.root:u2dctQHUVuOXcZhS@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/Cross_Market_Analysis")

crypto_df.to_sql ("cryptocurrencies", con = engine, if_exists = "replace", index = False) # push crypto_df to sqlite

top_coins_df.to_sql ("top_coins", con = engine, if_exists = "replace", index = False)

oil_df.to_sql ("oil_prices", con = engine, if_exists = "replace", index = False)

stks_df.to_sql ("stks_prices", con = engine, if_exists = "replace", index = False)

"""# **Querries where mentioned in project file**

### **Cryptocurrencies**
"""

# show/read cryptocurrencies table
df = pd.read_sql("SELECT * FROM  cryptocurrencies;", engine)
df

# 1. Find the top 5 cryptocurrencies by market cap.
top_cryp = pd.read_sql (
    """SELECT coin_name, MAX(market_cap) AS market_cap FROM cryptocurrencies WHERE market_cap IS NOT NULL GROUP BY coin_name ORDER BY market_cap DESC LIMIT 5;""", engine)

top_cryp

# 2. List all coins where circulating supply exceeds 90% of total supply.

cir_sup = pd.read_sql (
    """SELECT * FROM cryptocurrencies WHERE total_supply IS NOT NULL AND total_supply > 0 AND circulating_supply >= 0.9 * total_supply AND circulating_supply IS NOT NULL;""", engine)

cir_sup

# 3. Get coins that are within 10% of their all-time-high (ATH).

ath = pd.read_sql(""" SELECT * FROM cryptocurrencies WHERE current_price >= 0.9 * ath
AND current_price IS NOT NULL ORDER BY current_price DESC;
""", engine)

ath

# 4. Find the average market cap rank of coins with volume above $1B.

df = pd.read_sql ("SELECT AVG(market_cap_rank) FROM cryptocurrencies WHERE total_volume > 1000000000 AND total_volume IS NOT NULL;", engine)

df

# 5. Get the most recently updated coin.

df = pd.read_sql ("SELECT * FROM cryptocurrencies ORDER BY last_updated DESC LIMIT 1;", engine)

df

"""### **Crypto_Prices (Daily Prices of Top Coins)**"""

df = pd.read_sql("SELECT * FROM  top_coins;", engine)
df

# 1. Find the highest daily price of Bitcoin in the last 365 days.

df = pd.read_sql(
    """SELECT coin_id, MAX(price) AS highest_daily_price FROM top_coins WHERE coin_id = 'bitcoin' AND DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);""", engine
)

df

# 2. Calculate the average daily price of Ethereum in the past 1 year.

df = pd.read_sql ("SELECT coin_id, AVG(price) as Avg_price FROM top_coins WHERE coin_id = 'ethereum' AND DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);", engine)

df

# 3. Show the daily price trend of Bitcoin in January 2025. (or change the month and year according you your data)

df = pd.read_sql(
    """SELECT coin_id, price AS daily_price, date FROM top_coins WHERE coin_id = 'bitcoin' AND Date BETWEEN '2025-01-01' AND '2026-02-28' ORDER BY Date;""", engine)

df

# 4. Find the coin with the highest average price over 1 year.

df = pd.read_sql (
    """SELECT coin_id, AVG(price) AS avg_price FROM top_coins WHERE DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY)
    GROUP BY coin_id ORDER BY avg_price DESC LIMIT 1;""",
    engine)

df

# 5. Get the % change in Bitcoin’s price between Feb 2025 and Feb 2026.

df = pd.read_sql(
    """ SELECT
        (
            (MAX(CASE WHEN DATE(date) BETWEEN '2026-02-01' AND '2026-02-28' THEN price END)
                -
                MAX(CASE WHEN DATE(date) BETWEEN '2025-02-01' AND '2025-02-28' THEN price END)
            )
            /
            MAX(CASE WHEN DATE(date) BETWEEN '2025-02-01' AND '2025-02-28' THEN price END)
        ) * 100 AS percentage_change
    FROM top_coins WHERE coin_id = 'bitcoin';""",
    engine
)

df

"""### **Oil_Price**"""

df = pd.read_sql ("SELECT * FROM  oil_prices;", engine)
df

# 1. Find the highest oil price in the last 5 years.

df = pd.read_sql(""" SELECT MAX(price) AS highest_price FROM oil_prices WHERE date >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);
""", engine)

df

# 2. Get the average oil price per year.

df = pd.read_sql("""SELECT YEAR(date) AS year, AVG(price) AS avg_price
FROM oil_prices GROUP BY YEAR(date) ORDER BY YEAR(date);""", engine)

df

# 3. Show oil prices during COVID crash (March–April 2020).

df = pd.read_sql("""SELECT date, price FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-30' ORDER BY date;
""", engine)

df

# 4. Find the lowest price of oil in the last 10 years.

df = pd.read_sql("""SELECT date, price FROM oil_prices
WHERE price = (SELECT MIN(price) FROM oil_prices WHERE date >= DATE_SUB(CURDATE(), INTERVAL 10 YEAR));
""", engine)

df

# 5. Calculate the volatility of oil prices (max-min difference per year).

df = pd.read_sql("""SELECT YEAR(date) AS year, MAX(price) AS highest_price, MIN(price) AS lowest_price, MAX(price) - MIN(price) AS volatility
FROM oil_prices GROUP BY YEAR(date) ORDER BY YEAR(date);
""", engine)

df

"""### **Stock_Prices**"""

df = pd.read_sql("SELECT * FROM stks_prices;", engine)
df

# 1. Get all stock prices for a given ticker

df = pd.read_sql(""" SELECT * FROM stks_prices WHERE Ticker IN ('^IXIC', '^NSEI', '^GSPC')
AND Open IS NOT NULL AND High IS NOT NULL
AND Low IS NOT NULL AND Close IS NOT NULL
AND Volume IS NOT NULL ORDER BY Date;
""", engine)

df

# 2. Find the highest closing price for NASDAQ (^IXIC)

df = pd.read_sql ("SELECT MAX(close) AS highest_closing_price FROM stks_prices WHERE ticker = '^IXIC';", engine)

df

# 3. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

df = pd.read_sql ("""SELECT date, high - low AS price_difference FROM stks_prices
WHERE ticker = '^GSPC' ORDER BY price_difference DESC LIMIT 5
;""", engine)

df

# 4. Get monthly average closing price for each ticker

df = pd.read_sql("""
SELECT Ticker,
       DATE_FORMAT(Date, '%Y-%m') AS month,
       AVG(Close) AS avg_closing_price
FROM stks_prices
WHERE Close IS NOT NULL AND Date IS NOT NULL
GROUP BY Ticker, month ORDER BY Ticker, month;
""", engine)

df

"""### **Joint Querries**"""

# 1. Compare Bitcoin vs Oil average price in 2025.

df = pd.read_sql("""
SELECT
    DATE(c.date) AS date,
    c.price AS btc_close,
    o.price AS oil_close
FROM top_coins c
LEFT JOIN oil_prices o
    ON DATE(c.date) = DATE(o.date)
WHERE c.coin_id = 'bitcoin'
AND c.price IS NOT NULL
AND o.price IS NOT NULL
ORDER BY date;
""", engine)

df

# 2. Check if Bitcoin moves with S&P 500 (correlation idea).

df = pd.read_sql("""
SELECT
    DATE(t.date) AS date,
    t.price AS btc_close,
    s.Close AS stks_close
FROM top_coins t
LEFT JOIN stks_prices s
    ON DATE(t.date) = DATE(s.Date)
   AND s.Ticker = '^GSPC'
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

# 3. Compare Ethereum and NASDAQ daily prices for 2025.

df = pd.read_sql("""
SELECT
    DATE(t.date) AS date,
    t.price AS eth_close,
    s.Close AS nasdaq_close
FROM top_coins t
JOIN stks_prices s
    ON DATE(t.date) = DATE(s.Date)
WHERE t.coin_id = 'ethereum'
AND s.Ticker = '^IXIC'
AND YEAR(t.date) = 2025
AND t.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date;
""", engine)


df

# 4. Find days when oil price spiked and compare with Bitcoin price change.

df = pd.read_sql ("""SELECT date(o.Date) AS date,
    o.Price AS oil_price,
    t.price AS btc_price
FROM oil_prices o
JOIN top_coins t
    ON date(o.Date) = date(t.Date)
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND o.price IS NOT NULL
ORDER BY date;
""", engine)

df

# 5. Compare top 3 coins daily price trend vs Nifty (^NSEI).

df = pd.read_sql ("""
SELECT
    date(c.Date) AS date,
    c.coin_id AS coins,
    c.price AS coin_prices,
    s.Close AS nifty_close
FROM top_coins c
JOIN stks_prices s
    ON date(c.Date) = date(s.Date)
WHERE c.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
  AND s.Ticker = '^NSEI'
  AND c.price IS NOT NULL
  AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

# 6. Compare stock prices (^GSPC) with crude oil prices on the same dates


df = pd.read_sql("""
SELECT
    date(s.Date) AS date,
    s.Close AS nifty_close,
    o.Price AS oil_price
FROM stks_prices s
JOIN oil_prices o
    ON date(s.Date) = date(o.Date)
WHERE s.Ticker = '^GSPC'
AND s.Close IS NOT NULL
AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df

# 7. Correlate Bitcoin closing price with crude oil closing price (same date)

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS btc_price,
    o.Price AS oil_price
FROM top_coins t
JOIN oil_prices o
    ON date(t.Date) = date(o.Date)
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df

# 8. Compare NASDAQ (^IXIC) with Ethereum price trends

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS eth_price,
    s.Close AS ixic_close
FROM top_coins t
JOIN stks_prices s
    ON date(t.Date) = date(s.Date)
WHERE t.coin_id = 'ethereum'
  AND s.Ticker = '^IXIC'
  AND t.price IS NOT NULL
  AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

# 9. Join top 3 crypto coins with stock indices for 2025
df = pd.read_sql("""
SELECT
    DATE(c.Date) AS date,
    c.coin_id AS crypto_coin,
    c.price AS crypto_price,
    s.Ticker AS stock_index,
    s.Close AS stock_close
FROM top_coins c
JOIN stks_prices s
    ON DATE(c.Date) = DATE(s.Date)
WHERE c.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
AND s.Ticker IN ('^GSPC', '^IXIC', '^NSEI')
AND YEAR(c.Date) = 2025
AND c.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date, crypto_coin;
""", engine)

df

# 10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS btc_price,
    s.Close AS stk_close,
    o.Price AS oil_price
FROM top_coins t
JOIN stks_prices s
    ON date(t.Date) = date(s.Date)
JOIN oil_prices o
    ON date(t.Date) = date(o.Date)
WHERE t.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
  AND t.price IS NOT NULL
  AND s.Close IS NOT NULL
  AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df